app/models/instrument.rb, app/models/rehearsal.rb, app/models/request.rb, app/models/role.rb, app/models/skill.rb, app/models/user.rb, db/migrate/20210225184524_add_username_to_users.rb, db/migrate/20210225184819_add_bio_to_users.rb, db/migrate/20210225184920_create_instruments.rb, db/migrate/20210225185205_create_skills.rb, db/migrate/20210225185330_create_rehearsals.rb, db/migrate/20210225185517_create_roles.rb, db/migrate/20210225190004_create_requests.rb, db/schema.rb, test/models/instrument_test.rb, test/models/rehearsal_test.rb, test/models/request_test.rb, test/models/role_test.rb, test/models/skill_test.rb
=> models made

db/seeds.rb
=> created our first seed file

app/controllers/application_controller.rb
=> Permitted bio and username of user

app/models/instrument.rb, app/models/rehearsal.rb, app/models/request.rb, app/models/role.rb, app/models/user.rb
Hi, I've put in some validations on the models and have written some scopes which I've tested in rails c and i think/hope they work. They will hopefully make it easier for us to get information from the Database for each page of the app.
=> Wrote model validations and some scopes

Gemfile.lock, app/models/rehearsal.rb, app/models/role.rb, app/models/user.rb, db/seeds.rb
Hi, I realised that the model validations I wrote caused some errors with the seed. (e.g. now, users must have a username, rehearsals must have date_time etc). So I added those fields in the seed file, and also created a couple more rehearsals for the index page. PLease can you check?
=> seed now works with new model validations

app/controllers/rehearsals_controller.rb, app/views/rehearsals/_form.html.erb, app/views/rehearsals/edit.html.erb, app/views/rehearsals/index.html.erb, app/views/rehearsals/new.html.erb, app/views/rehearsals/show.html.erb
Hi, I created a basic rehearsals controller and views. Can you review, please?
=> Created basic rehearsals controller and views

app/views/rehearsals/index.html.erb
Hi, I updated the rehearsals view with upcoming and suggested rehearsals. Can you review, please?
=> Updated the rehearsals view with upcoming and suggested rehearsals

config/routes.rb
=> Added edit and update to roles routes

app/controllers/rehearsals_controller.rb
Called .uniq on suggested_rehearsals to avoid duplicated results!
=> Got rid of duplicated suggested rehearsals

app/views/shared/_banner.html.erb
If logged in, the page displays the following:
=> Home page view for logged-in user

app/controllers/rehearsals_controller.rb, app/views/rehearsals/show.html.erb
On rehearsal show page you can see a list of attendees, the organiser, and remaining spaces (including a 'request to join' button next to the instrument you play)
=> Put more information on show page

.gitignore, app/controllers/application_controller.rb, app/controllers/rehearsals_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/devise/registrations/edit.html.erb, app/views/rehearsals/show.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20210227151400_create_active_storage_tables.active_storage.rb, db/schema.rb
Users can attach an avatar. Displayed in navbar and on rehearsal showpage (organiser avatar)
=> Users can now upload an avatar

app/views/rehearsals/show.html.erb, app/views/users/show.html.erb
You can see somebody's profile picture on the profile page. 
On the rehearsal show page, you can see the avatar of the rehearsal organiser and click on their username to go to their profile page
=> Profile pic

app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
Put divs around login and signup forms (same as in garden escape)
=> Centred login and signup forms

app/models/user.rb
..which we could use for rehearsal history on profile page
=> past_rehearsals method in User

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/views/devise/registrations/edit.html.erb
=> tidied up the edit profile form

app/assets/stylesheets/components/_form.scss, app/controllers/skills_controller.rb, app/views/devise/registrations/edit.html.erb, config/routes.rb
Added ability on edit-profile form to toggle what instruments you play
=> User can add / delete what instruments they play

app/assets/stylesheets/components/_profile-page.scss, app/views/users/show.html.erb
It went a bit skew whiff, it looks much more presentable now :)
=> updated profile page

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/javascript/packs/application.js, app/javascript/plugins/init_flatpickr.js, app/views/layouts/application.html.erb, app/views/rehearsals/_form.html.erb, package.json, yarn.lock
Calendar input for datetime of rehearsal
=> Added flatpickr

app/assets/stylesheets/components/_edit-user.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_instrument_card.scss, app/views/devise/registrations/edit.html.erb
=> Added mini instrument icons to edit user skills form

app/assets/stylesheets/components/_banner.scss, app/views/shared/_banner.html.erb
Hey, I replaced the background image url with asset-url to fix the homepage display bug.
=> Banner image url replaced with asset-url

app/javascript/packs/application.js, app/javascript/plugins/init_autocomplete.js, app/views/rehearsals/_form.html.erb
you will require a yarn install
=> added search functionality

app/views/requests/index.html.erb, config/locales/en.yml
Hey, I've re-used the en.yml on the rehearsals index page (it was deleted accidentally in one of our previous commits).
=> Config > locales > en.yml file used in the rehearsals index

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card-rehearsal.scss, app/controllers/pages_controller.rb, app/views/pages/home.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_navbar.html.erb, db/schema.rb
updated home page. Possibly the Explore button should be bigger..?
=> Put upcoming rehearsals on home page and changed navbar content

app/assets/stylesheets/components/_navbar.scss, app/controllers/application_controller.rb, app/controllers/requests_controller.rb, app/javascript/controllers/counter_controller.js, app/javascript/controllers/hello_controller.js, app/javascript/controllers/index.js, app/javascript/packs/application.js, app/views/shared/_navbar.html.erb, package.json, yarn.lock
=> Request notification added

app/assets/stylesheets/components/_card-rehearsal.scss, app/views/rehearsals/index.html.erb, app/views/shared/_card_rehearsal.html.erb, app/views/shared/_spaces_card.html.erb
Some little tweaks:
-shortened address on rehearsal card
- made whole rehearsal card clickable
- added border on hover (pls delete if you don't like it!)
- user on attendees card is clickable, taking you to their profile
=> Shortened address on rehearsal card

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_profile-page.scss
Softer colour for h and p tags
=> Changed all title and p tags to almost-black colour

app/assets/stylesheets/components/_animated_musical_notes.scss, app/assets/stylesheets/components/_instrument_card.scss, app/assets/stylesheets/components/_profile-page.scss, app/controllers/rehearsals_controller.rb, app/controllers/roles_controller.rb, app/views/rehearsals/add_roles.html.erb, app/views/roles/_form.html.erb
=> Changed hover effects and spacing on roles page

app/assets/stylesheets/components/_instrument_card.scss, app/assets/stylesheets/pages/_rehearsal_form.scss
Made hover effects on instrument cards the same on different pages
=> Hover effects equal on all instrument cards

app/models/rehearsal.rb
Smaller max length for rehearsal title to keep rehearsal cards clean.
=> 25 characters max for rehearsal title

app/controllers/requests_controller.rb, app/controllers/roles_controller.rb, app/models/request.rb, app/views/requests/index.html.erb
request.status will return either 'Confirmed', 'Rejected' or 'Pending'.
Also - when you accept a user's request, all of the other users who requested that same role will be rejected
=> Request instance method

app/views/shared/_card_rehearsal.html.erb
Instrument pic displayed on rehearsal cards on index page
=> Instrument pic on index page rehearsal cards

app/views/users/show.html.erb
Fixed avatar setting on profile page
=> Profile pic avatar setting

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_my_request_card.scss, app/models/request.rb, app/views/rehearsals/show.html.erb, app/views/requests/index.html.erb, app/views/shared/_my_request_card.html.erb, config/locales/en.yml
=> Made my-request-card

app/views/pages/home.html.erb, app/views/rehearsals/index.html.erb, app/views/shared/_card_rehearsal.html.erb, app/views/shared/_my_request_card.html.erb, app/views/shared/_spaces_card.html.erb, app/views/users/show.html.erb
Found a bug when you go to other people's profile page, to do with rendering of rehearsal card
=> Fixed bug in rehearsal cards on profile page

app/javascript/plugins/init_mapbox.js, app/views/shared/_spaces_card.html.erb
Music icon removed from attendee card and no more zoom on the map
=> Remove music icon

app/views/shared/_navbar.html.erb
=> Explore link added to the navbar

app/assets/stylesheets/components/_my_request_card.scss, app/controllers/requests_controller.rb, app/models/request.rb, app/views/requests/index.html.erb, app/views/shared/_my_request_card.html.erb
On 'my requests' page, hover over a pending request you have made, and you'll be able to cancel that request
=> ability to cancel pending requests

app/views/devise/registrations/edit.html.erb, app/views/rehearsals/add_roles.html.erb
...on 'edit profile' page and 'add roles' page
=> Alphabetized instrument cards

app/assets/stylesheets/components/_my_request_card.scss, app/views/shared/_my_request_card.html.erb
all the request cards are clickable -> rehearsal show page
=> Request cards link to rehearsal show page

app/views/rehearsals/_form.html.erb, app/views/roles/_form.html.erb
can easily change the colour if you think another would be more suitable!
=> Used yellow open rehearsal button for next/back in form

app/assets/stylesheets/components/_request_card.scss, app/controllers/requests_controller.rb, app/models/rehearsal.rb, app/models/request.rb, app/views/requests/index.html.erb
Rehearsals with pending requests appear at the top of the inbox on my requests page
=> Ordered rehearsals by pending request count

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_rehearsal_edit.scss, app/views/rehearsals/edit.html.erb
Have put the same styling on edit rehearsal page as for edit user page
=> Decorated rehearsal edit page

app/assets/stylesheets/components/_instrument_card.scss, app/views/rehearsals/add_roles.html.erb
Finished button now stays beneath lineup div on the right
=> Finished button stays under lineup div

app/assets/stylesheets/components/_aninmated_musical_notes_v2.scss, app/assets/stylesheets/components/_index.scss, app/views/shared/_animated_muscial_notes-v2.html.erb, app/views/shared/_banner.html.erb
=> Banner music notes
